name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Download
         run: |
              mkdir -p fluid
              cd fluid
              $PATH=~/bin:$PATH
              repo init -u https://github.com/Project-Fluid/manifest.git -b fluid-11
              repo sync --force-sync --no-tags --no-clone-bundle -j$(nproc --all)
              ls

       - name: build
         continue-on-error: true
         run: |
              cd fluid
              . build/envsetup.sh
              lunch fluid_device-userdebug
              mka bacon
