name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         continue-on-error: true
         run: |
              mkdir -p ~/.repo
              PATH="${HOME}/.repo:${PATH}"
              curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.repo/repo
              chmod a+rx ~/.repo/repo  
              sudo apt install repo expect -y
              git clone https://android.googlesource.com/tools/repo
              ls
     
       - name: Download
         continue-on-error: true
         run: |
              ls
              cd repo
              ls
              git clone https://github.com/ponces/treble_experimentations
              mkdir pixel; cd pixel
              ls
              repo init -u https://github.com/Project-Fluid/manifest.git -b fluid-11
              git clone https://github.com/ponces/treble_patches -b eleven
              git clone https://github.com/rahulkhatri137/treble_build_pe -b eleven

       - name: Build
         continue-on-error: true
         run: |
              cd pixel
              bash treble_build_pe/buildbot_treble.sh
              ls
              cd builds
              ls
       - name: XZip AB and upload 
         run: |
              cd repo
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put main.py\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
