name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set Git Configs & Secrets
         run: |
              git config --global user.email ${{ secrets.GHMAIL }}
              git config --global user.name ${{ secrets.GHUSER }}
              git config --global credential.helper store
              echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
              sudo apt install expect -y

       - name: Download
         run: |
              git clone https://github.com/phhusson/treble_app

       - name: Build
         continue-on-error: true
         run: |
              cd treble_app
              bash build.sh
              ls

       - name: Upload 
         run: |
              cd treble_app
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.apk\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
              cd app
              ls
              cd build
              ls
              cd output
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.apk\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
