name: test

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/alpha.zip
  FILE_NAME:
  TZ: Asia/Kolkata

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Download
         run: |
              mkdir -p file

       - name: Decompress
         run: |
              cd file
              if [ "FILE=*.zip" ]; then
              echo "Enter url of file to download";
              else echo "Downloading your file. wait... it can take some seconds";
              fi
