name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set Git Configs & Secrets
         run: |
              aria2c https://mirror.rahul137.workers.dev/ZUI-HELIOS-25-10-GSI-AB/ErfanGSIs/output/ZUI-AB-10-20201025-HELIOSBAKERTOOLS.img
       
       - name: Build
         continue-on-error: true
         run: |
              mkdir -p output
              mv ZUI-AB-10-20201025-HELIOSBAKERTOOLS.img system.img
              sudo mount -t ext4 -o loop system.img output/
              ls ; cd output ; ls

       - name: Run
         run: |
              ls
