name: Sync

on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v3
       
       - name: Download
         run: |
          sudo chmod -R 777 ./
          ./git.sh ; sudo ./repo.sh ; sudo ./init.sh

       - name: Sync
         timeout-minutes: 1
         run: |
          sudo chmod a+rx ~/.bin/repo
          ~/.bin/repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
