name: test

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/alpha.zip
  FILE_NAME:
  TZ: Asia/Kolkata

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Download
         run: |
              mkdir -p file
              cd file
              if [ -z "$FILE_URL" ]; then
              echo "Enter url of file to download"
              exit 1;
              else echo "Downloading your file. wait... it can take some seconds/minutes"
              aria2c  $FILE_URL;
              fi

       - name: Decompress
         run: |
              cd file
              if [ -z "FILE=.zip"; then
              echo "Enter url of file to download";
              else echo "Downloading your file. wait... it can take some seconds";
              fi
