name: test

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/blueline-spb2.210513.007-factory-6c2e7c7f/blueline-spb2.210513.007/bootloader-blueline-b1c1-0.4-7266295.img
  FILE_NAME:
  F_NAME: test.img
  TZ: Asia/Kolkata

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
              if [ -z "$FILE_NAME" ]; then echo "NULL"; else echo "Not NULL"; fi
              [ -z "$F_NAME" ] echo "NULL" || echo "Not NULL"
