name: test

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/ImsService.apk
  FILE_NAME:
  TZ: Asia/Kolkata

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Download
         run: |
          git clone --recurse-submodules https://github.com/rahulkhatri137/ErfanGSIs
          cd ErfanGSIs/build; ls ; ls vendor
