name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set Git Configs & Secrets
         run: |
              git config --global user.email ${{ secrets.GHMAIL }}
              git config --global user.name ${{ secrets.GHUSER }}
              git config --global credential.helper store
              echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       
       - name: Build
         continue-on-error: true
         run: |
              git clone https://rahulkhatri137:${{ secrets.GH_TOKEN }}@github.com/rahulkhatri137/android-tool
              sudo install simg2img
              ls

       - name: Run
         run: |
              ls
